apiVersion: apps/v1
kind: Deployment
metadata:
  name: wokte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wokte
  template:
    metadata:
      labels:
        app: wokte
    spec:
      containers:
      - image: okteto.dev/wokte:latest
        name: wokte
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "dfad4253-eef3-489d-9a2d-8da935fa356c"
        - name: Vless_Path
          value: "/jxfiuygdr7fuyt"
        - name: Vmess_UUID
          value: "dfad4253-eef3-489d-9a2d-8da935fa356c"
        - name: Vmess_Path
          value: "/76rtd76t876rfc"
        - name: Share_Path
          value: "/v2link"
